name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00AM GMT-5
    - cron: '*/5 * * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: 9699d33508146d528ebf1e6d186c549ceee70328
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "True"
